export const LANGUAGE_MAP = {
  en: "English",
  pt: "Portuguese",
  es: "Spanish",
  ru: "Russian",
  tr: "Turkish",
  fr: "French",
  ar: "Arabic",
  ht: "Haitian Creole",
  zh: "Chinese",
  de: "German",
  it: "Italian",
  nl: "Dutch",
  ja: "Japanese",
  ko: "Korean",
  hi: "Hindi",
  bn: "Bengali",
  ur: "Urdu",
  ta: "Tamil",
  te: "Telugu",
  vi: "Vietnamese",
  pl: "Polish",
  uk: "Ukrainian",
  ro: "Romanian",
  el: "Greek",
  he: "Hebrew",
  hu: "Hungarian",
  sv: "Swedish",
  th: "Thai",
  fi: "Finnish",
  da: "Danish",
  no: "Norwegian",
  cs: "Czech",
  id: "Indonesian",
  ms: "Malay",
  fa: "Persian",
  sr: "Serbian",
  bg: "Bulgarian",
  hr: "Croatian",
  sk: "Slovak",
  lt: "Lithuanian",
  sl: "Slovenian",
  et: "Estonian",
  lv: "Latvian",
};

export const REVERSE_LANGUAGE_MAP = Object.fromEntries(
  Object.entries(LANGUAGE_MAP).map(([key, value]) => [value, key])
);
